/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Admin/AdminUserView': RouteRecordInfo<'/Admin/AdminUserView', '/Admin/AdminUserView', Record<never, never>, Record<never, never>>,
    '/LoginView': RouteRecordInfo<'/LoginView', '/LoginView', Record<never, never>, Record<never, never>>,
    '/SignUpView': RouteRecordInfo<'/SignUpView', '/SignUpView', Record<never, never>, Record<never, never>>,
    '/User/FriendsView': RouteRecordInfo<'/User/FriendsView', '/User/FriendsView', Record<never, never>, Record<never, never>>,
    '/User/SearchView': RouteRecordInfo<'/User/SearchView', '/User/SearchView', Record<never, never>, Record<never, never>>,
    '/User/UserView': RouteRecordInfo<'/User/UserView', '/User/UserView', Record<never, never>, Record<never, never>>,
  }
}
