GET http://localhost:3000/about

###
GET http://localhost:3000/api/v1/users

###
GET http://localhost:3000/api/v1/users/30

###
DELETE http://localhost:3000/api/v1/users/1

###
POST http://localhost:3000/api/v1/users
Content-Type: application/json

{