# this is a comment. Three hashes are to start a new request. 
# Everything defaults to GET.
# package.json for the server must be in the root.

###
GET https://google.com

###
POST https://localhost:3000/api/v1/users/signup

# Fix error getaddrinfo ENOTFOUND localhost3000.

###
GET http://localhost3000/users
